In [12]:
import pandas as pd 
#We use pandas because it makes data analysis and manipulation in Python much easier, faster, and cleaner.
# import numpy as np 
# #imports NumPy, a library used for fast numerical computation, array manipulation, and mathematical operations — and np is just a short alias to make code cleaner.
# import matplotlib.pyplot as plt 
# #imports Matplotlib’s plotting module (pyplot) and lets you create visualizations like line charts, bar charts, and scatter plots using the short alias plt.
# import seaborn as sns 
# #imports Seaborn, a data visualization library built on top of Matplotlib, allowing you to create beautiful, statistical plots easily using the short alias sns.
# import warnings 
# #imports Python’s warnings module and disables the display of warning messages during code execution.
# warnings.filterwarnings("ignore")

In [20]:
import pandas as pd

df = pd.read_csv("airlines_flights_data.csv")

In [21]:
df.describe

<bound method NDFrame.describe of          index   airline   flight source_city departure_time stops  \
0            0  SpiceJet  SG-8709       Delhi        Evening  zero
1            1  SpiceJet  SG-8157       Delhi  Early_Morning  zero
2            2   AirAsia   I5-764       Delhi  Early_Morning  zero
3            3   Vistara   UK-995       Delhi        Morning  zero
4            4   Vistara   UK-963       Delhi        Morning  zero
...        ...       ...      ...         ...            ...   ...
300148  300148   Vistara   UK-822     Chennai        Morning   one
300149  300149   Vistara   UK-826     Chennai      Afternoon   one
300150  300150   Vistara   UK-832     Chennai  Early_Morning   one
300151  300151   Vistara   UK-828     Chennai  Early_Morning   one
300152  300152   Vistara   UK-822     Chennai        Morning   one

         arrival_time destination_city     class  duration  days_left  price
0               Night           Mumbai   Economy      2.17          1   5953
1             Morning           Mumbai   Economy      2.33          1   5953
2       Early_Morning           Mumbai   Economy      2.17          1   5956
3           Afternoon           Mumbai   Economy      2.25          1   5955
4             Morning           Mumbai   Economy      2.33          1   5955
...               ...              ...       ...       ...        ...    ...
300148        Evening        Hyderabad  Business     10.08         49  69265
300149          Night        Hyderabad  Business     10.42         49  77105
300150          Night        Hyderabad  Business     13.83         49  79099
300151        Evening        Hyderabad  Business     10.00         49  81585
300152        Evening        Hyderabad  Business     10.08         49  81585

[300153 rows x 12 columns]>

In [22]:
df.head(10)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
5,5,Vistara,UK-945,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5955
6,6,Vistara,UK-927,Delhi,Morning,zero,Morning,Mumbai,Economy,2.08,1,6060
7,7,Vistara,UK-951,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6060
8,8,GO_FIRST,G8-334,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5954
9,9,GO_FIRST,G8-336,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954

In [32]:
df.tail(10)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
300143,300143,Air_India,AI-440,Chennai,Early_Morning,one,Night,Hyderabad,Business,17.42,49,51345
300144,300144,Air_India,AI-539,Chennai,Evening,one,Morning,Hyderabad,Business,18.92,49,51345
300145,300145,Air_India,AI-430,Chennai,Morning,one,Morning,Hyderabad,Business,23.08,49,51345
300146,300146,Air_India,AI-440,Chennai,Early_Morning,one,Morning,Hyderabad,Business,26.83,49,51345
300147,300147,Air_India,AI-569,Chennai,Early_Morning,one,Night,Hyderabad,Business,17.25,49,68739
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [23]:
df.shape #Find the total (Row & Columns)

(300153, 12)

In [24]:
df.columns

Index(['index', 'airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class', 'duration', 'days_left',
       'price'],
      dtype='object')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   index             300153 non-null  int64
 1   airline           300153 non-null  object
 2   flight            300153 non-null  object
 3   source_city       300153 non-null  object
 4   departure_time    300153 non-null  object
 5   stops             300153 non-null  object
 6   arrival_time      300153 non-null  object
 7   destination_city  300153 non-null  object
 8   class             300153 non-null  object
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB

In [26]:
df.isnull().sum()

index               0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

In [27]:
df.describe()

               index       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

In [28]:
df.columns

Index(['index', 'airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class', 'duration', 'days_left',
       'price'],
      dtype='object')

In [29]:
df.dtypes

index                 int64
airline              object
flight               object
source_city          object
departure_time       object
stops                object
arrival_time         object
destination_city     object
class                object
duration            float64
days_left             int64
price                 int64
dtype: object

In [30]:
df.size

3601836

In [31]:
df.drop_duplicates(inplace=True)

In [33]:
airline_column = df['airline']

In [36]:
print(airline_column.unique())

['SpiceJet' 'AirAsia' 'Vistara' 'GO_FIRST' 'Indigo' 'Air_India']

In [37]:
print(airline_column.value_counts())

airline
Vistara      127859
Air_India     80892
Indigo        43120
GO_FIRST      23173
AirAsia       16098
SpiceJet       9011
Name: count, dtype: int64

In [38]:
flight_column=df["flight"]
print(flight_column.value_counts())

flight
UK-706     3235
UK-772     2741
UK-720     2650
UK-836     2542
UK-822     2468
           ...
SG-9923       1
6E-6474       1
6E-865        1
G8-705        1
G8-107        1
Name: count, Length: 1561, dtype: int64

In [40]:
destination_city_column = df['destination_city']
print(destination_city_column.unique())

['Mumbai' 'Bangalore' 'Kolkata' 'Hyderabad' 'Chennai' 'Delhi']

In [42]:
source_city_column = df['source_city']

print(source_city_column.unique())

['Delhi' 'Mumbai' 'Bangalore' 'Kolkata' 'Hyderabad' 'Chennai']